config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :index]

  get '/login'=> 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  resources :locations
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user, :optional => true
	belongs_to :location, :optional => true
end

app/models/location.rb
class Location < ApplicationRecord
    belongs_to :user, :optional => true
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, :presence => true, :uniqueness => true
    has_secure_password
    has_many :locations
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user
    
    private
    def fetch_user
        @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
        session[:user_id] = nil unless @current_user.present? 
    end
    def check_in_log
        redirect_to login_path unless @current_user.present?
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def index
    @comments = Comment.all
  end

  def edit
    @comment = Comment.find params[:id]
  end

  def create
    comment = Comment.create comment_params
    comment_params
    redirect_to comment
  end

  def updated
    comment = Coment.find params[:id]
    comment = Comment.update comment_params
    redirect_to comment
  end


  def show
    @comment =Comment.find params[:id]
  end



  private
  def comment_params
    params.require(:params).permit(:content, :date, :like, :location_id, :user_id)
  end


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :check_in_log
  
  def index
    # @locations = Location.user_id.find @current_user.id
    @locations = Location.where(user_id: @current_user.id)
  end

  def new
    @location = Location.new
  end

  def create
    location = Location.create location_params
    @current_user.locations << location #assign user 
    # location = @current_user.locations.create location_params
    redirect_to location    #location_path params[:id] 
   
  end

  def show
    @location = Location.find params[:id]
  end

  def edit
    @location = Location.find params[:id]
  end
    
  def destroy
    location = Location.find params[:id]
    location.destroy
    redirect_to locations_path
  end

  private
  def location_params
    params.require(:location).permit(:address, :harvest, :image, :note )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
 
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end
  def destroy
    session[:user_id] =nil
    redirect_to login_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      #if user data base sucesffuly then redirec to root
      redirect_to root_path ##this could be any where user home pages?????
    else #if there are problems, user can try again
      render :new
    end
  end

  private
  def user_params
  params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.label :date %>
    <%= f.text_field :date, :placeholder => "YYYY-MM-DD" %>
    <%= f.label :like %>
    <%= f.text_field :like %>

    <%= f.submit "Create comment" %>

    <% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>All comments</h1>
<% @comments.each do |comment| %>
    <ul>
        <li>
            <%= link_to comment.content, comment %>
        </li>
    </ul>
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render :partial => 'form' %>

app/views/comments/show.html.erb
<h1>Comment details</h1>

<ul>
    <li>Comment: <%= @comment.content %></li>
    <li>Date: <%= @comment.date  %></li>
    <li>Likes:<%= @comment.like %></li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to "HOME", root_path %> |
      <% if @current_user.present? %>
        <%= link_to "New location", new_location_path %>
        <%= link_to "Your location", locations_path %>
        <%= link_to "Sing out #{ @current_user.name}", login_path, :method => 'delete' %>
      <% else %>
        <%= link_to "Sign Up", new_user_path %>
        <%= link_to 'Sign In',login_path %>
      <% end %>
      

    </nav>
      
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
    <%= f.label :address %>
    <%= f.text_field :address, :required => true %>
    <%= f.label :harvest %>
    <%= f.text_field :harvest,:required => true %>
    <%= f.label :image %>
    <%=  f.text_field :image, :required => true %>
    <%= f.label :note %>
    <%= f.text_field :note, :required => true %>

<%= f.submit %>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit your location</h1>
<%= render :partial => 'form' %>

app/views/locations/index.html.erb
<h1>Your locations</h1>


    <% @locations.each do |location| %> 
        <%= link_to image_tag(location.image || "https://loremflickr.com/320/240/flower", :class => 'thumb'), location %>
    <% end %>

app/views/locations/new.html.erb
<h1>Create your locations!</h1>
<%= render :partial => 'form' %>

app/views/locations/show.html.erb
<h1><%= @location.address %></h1>
<%= image_tag @location.image, :class => 'feature' %>
<ul>
    <li>Location:<%= @location.address %> </li>
    <li>Harvest: <%= @location.harvest %></li>
    <li>note: <%= @location.note %></li>
</ul>
<% if @current_user.id == @location.user_id %>

<div class="controls">
    <%= link_to "Edit location", edit_location_path %>
    <%= link_to "Deleter Location", @location, :method => 'delete', :data => {:confirm => "Are you sure?"}%>


</div>
<% end %>

app/views/pages/home.html.erb
<h1>Urban ForaginApp</h1>
<% if @current_user.present?%>
    <h2> Hello, <%=  @current_user.email %> </h2>
<% end%>

app/views/session/new.html.erb
<h1>Log In</h1>

<%= form_tag login_path do %>
    <%= label_tag :email %>
    <%= email_field_tag :email %>

    <%= label_tag :password %>
    <%= password_field_tag :password %>

    <%= submit_tag "Sign In" %>


<%  end %>

app/views/users/index.html.erb
<h1> All Users</h1>

<%= @users.each do |user| %>
<p> <%=  users.email %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign In</h1>
<% if @user.errors.any? %>
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ol>
<% end %>
<%= form_for @user do|f| %>
    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit "Sign UP!" %>
<% end%>